[package]
name = "hotfuzz-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dumbfuzz = "1.0.0"
preftree = "0.1.0"
unicode-segmentation = { version = "1.11.0", features = ["no_std"] }
